# Generated by Django 4.1.4 on 2022-12-15 21:46

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "subspecialty_modality",
                    models.CharField(
                        choices=[
                            ("CT", "CT"),
                            ("MR", "MR"),
                            ("XA", "XA"),
                            ("CR", "CR"),
                            ("DX", "DX"),
                            ("PET", "PET"),
                            ("NM", "NM"),
                            ("US", "US"),
                            ("RF", "RF"),
                            ("ECG", "ECG"),
                            ("SC", "SC"),
                            ("MG", "MG"),
                            ("RTSTRUCT", "RSTRUCT"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "subspecialty_body_part",
                    models.CharField(
                        choices=[
                            ("ABDOMEN", "ABDOMEN"),
                            ("ANKLE", "ANKLE"),
                            ("BACK", "BACK"),
                            ("BREAST", "BREAST"),
                            ("CHEST", "CHEST"),
                            ("WHOLEBODY", "WHOLEBODY"),
                            ("FOOT", "FOOT"),
                            ("HAND", "HAND"),
                            ("HEAD", "HEAD"),
                            ("HIP", "HIP"),
                            ("KNEE", "KNEE"),
                            ("LEG", "LEG"),
                            ("NECK", "NECK"),
                            ("SHOULDER", "SHOULDER"),
                            ("SPINE", "SPINE"),
                            ("ARM", "ARM"),
                            ("UTERUS", "UTERUS"),
                            ("WRIST", "WRIST"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sla_goal", models.FloatField()),
                ("revenue_goal", models.PositiveIntegerField()),
                ("studies_goal", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.TimeField()),
                ("revenue", models.PositiveIntegerField()),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("CT", "CT"),
                            ("MR", "MR"),
                            ("XA", "XA"),
                            ("CR", "CR"),
                            ("DX", "DX"),
                            ("PET", "PET"),
                            ("NM", "NM"),
                            ("US", "US"),
                            ("RF", "RF"),
                            ("ECG", "ECG"),
                            ("SC", "SC"),
                            ("MG", "MG"),
                            ("RTSTRUCT", "RSTRUCT"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        choices=[
                            ("ABDOMEN", "ABDOMEN"),
                            ("ANKLE", "ANKLE"),
                            ("BACK", "BACK"),
                            ("BREAST", "BREAST"),
                            ("CHEST", "CHEST"),
                            ("WHOLEBODY", "WHOLEBODY"),
                            ("FOOT", "FOOT"),
                            ("HAND", "HAND"),
                            ("HEAD", "HEAD"),
                            ("HIP", "HIP"),
                            ("KNEE", "KNEE"),
                            ("LEG", "LEG"),
                            ("NECK", "NECK"),
                            ("SHOULDER", "SHOULDER"),
                            ("SPINE", "SPINE"),
                            ("ARM", "ARM"),
                            ("UTERUS", "UTERUS"),
                            ("WRIST", "WRIST"),
                        ],
                        max_length=16,
                    ),
                ),
                ("sla", models.IntegerField()),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        related_name="studies_assigned", to="core.user"
                    ),
                ),
            ],
        ),
    ]
