# Generated by Django 4.1.4 on 2022-12-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="studies_assigned", to="core.user"
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="body_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ABDOMEN", "ABDOMEN"),
                    ("ANKLE", "ANKLE"),
                    ("BACK", "BACK"),
                    ("BREAST", "BREAST"),
                    ("CHEST", "CHEST"),
                    ("WHOLEBODY", "WHOLEBODY"),
                    ("FOOT", "FOOT"),
                    ("HAND", "HAND"),
                    ("HEAD", "HEAD"),
                    ("HIP", "HIP"),
                    ("KNEE", "KNEE"),
                    ("LEG", "LEG"),
                    ("NECK", "NECK"),
                    ("SHOULDER", "SHOULDER"),
                    ("SPINE", "SPINE"),
                    ("ARM", "ARM"),
                    ("UTERUS", "UTERUS"),
                    ("WRIST", "WRIST"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="modality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CT", "CT"),
                    ("MR", "MR"),
                    ("XA", "XA"),
                    ("CR", "CR"),
                    ("DX", "DX"),
                    ("PET", "PET"),
                    ("NM", "NM"),
                    ("US", "US"),
                    ("RF", "RF"),
                    ("ECG", "ECG"),
                    ("SC", "SC"),
                    ("MG", "MG"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="revenue",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="study",
            name="sla",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="study",
            name="timestamp",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="revenue_goal",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="sla_goal",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="studies_goal",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="subspecialty_body_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ABDOMEN", "ABDOMEN"),
                    ("ANKLE", "ANKLE"),
                    ("BACK", "BACK"),
                    ("BREAST", "BREAST"),
                    ("CHEST", "CHEST"),
                    ("WHOLEBODY", "WHOLEBODY"),
                    ("FOOT", "FOOT"),
                    ("HAND", "HAND"),
                    ("HEAD", "HEAD"),
                    ("HIP", "HIP"),
                    ("KNEE", "KNEE"),
                    ("LEG", "LEG"),
                    ("NECK", "NECK"),
                    ("SHOULDER", "SHOULDER"),
                    ("SPINE", "SPINE"),
                    ("ARM", "ARM"),
                    ("UTERUS", "UTERUS"),
                    ("WRIST", "WRIST"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="subspecialty_modality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CT", "CT"),
                    ("MR", "MR"),
                    ("XA", "XA"),
                    ("CR", "CR"),
                    ("DX", "DX"),
                    ("PET", "PET"),
                    ("NM", "NM"),
                    ("US", "US"),
                    ("RF", "RF"),
                    ("ECG", "ECG"),
                    ("SC", "SC"),
                    ("MG", "MG"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
