# Generated by Django 4.1.4 on 2022-12-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_study_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="timestamp",
            field=models.DateField(blank=True, null=True),
        ),
    ]
